### ISSUE TITLE
How to reproduce the curves in the paper?

### ISSUE THREAD

**Issue by chongyi-zheng** [jhejna/hierarchical_morphology_transfer#3] opened 2020-09-28 09:03 UTC
I just want to know the command line instructions to reproduce the results in the paper.
I got this error with the command in ReadMe

```
python scripts/train_model.py --env Ant_High --alg SAC -t 200000 --time-limit 50
```

```
gym.error.Error: Attempted to look up malformed environment ID: b'Ant_High'. (Currently all IDs must be of the form ^(?:[\w:-]+\/)?([\w:.-]+)-v(\d+)$.)
```
I think there is something wrong with this function

https://github.com/jhejna/hierarchical_morphology_transfer/blob/fd8429dbc57f320526637dd8e3a5590cf766f723/bot_transfer/utils/loader.py#L211

**Comment by jhejna** [comment] 2020-09-28 18:09
Thanks for pointing this out! I believe the issue is not in the code, but rather with the command specified in the readme. Specifically, before training a high level policy, you need to provide a low-level for it to use. This is done with the `--policy` argument. I'm updating the readme and closing this for now, feel free to reopen it if issues persist.

**Closed as completed by jhejna** 2020-09-28 18:09 UTC
